$(document).ready(function(){
    $(".design-image").click(function(){
        $(".design-image").fadeIn("slow","linear").hide();
        $("#design").show();
    });
    $("#design").click(function(){
        $("#design").fadeOut("swing");
        $(".design-image").fadeIn("slow","swing");
    })
});

$(document).ready(function(){
    $(".dev-image").click(function(){
        $(".dev-image").fadeIn("slow","linear").hide();
        $("#development").show();
    });
    $("#development").click(function(){
        $("#development").fadeOut("swing");
        $(".dev-image").fadeIn("slow","swing");
    })
});
$(document).ready(function(){
    $(".product-image").click(function(){
        $(".product-image").fadeIn("slow","linear").hide();
        $("#management").show();
    });
    $("#management").click(function(){
        $("#management").fadeOut("swing");
        $(".product-image").fadeIn("slow","swing");
    })
});
